!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 32
  - - clip_range
    - 0.3
  - - ent_coef
    - 7.52585e-08
  - - gae_lambda
    - 1.0
  - - gamma
    - 0.9
  - - learning_rate
    - 0.000104019
  - - max_grad_norm
    - 0.9
  - - n_envs
    - 8
  - - n_epochs
    - 5
  - - n_steps
    - 512
  - - n_timesteps
    - 1000000.0
  - - normalize
    - true
  - - policy
    - MultiInputPolicy
  - - policy_kwargs
    - dict(net_arch=[256, 256])
  - - vf_coef
    - 0.950368
